### ISSUE TITLE
Normalizing Devanagari markup in wil.txt

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/WIL#5]
In the Wilson dictionary, printed Devanagari text is represented in the digitization wil.txt as `{#X#}`.  Moreover, in almost all cases, this markup is *closed* within each line of the digitization.

For further analysis, it is helpful to change the markup for those 125+ cases where the Devanagari markup is not closed within a line, so that the result is that the closure property is universal.

Here is the gist of the simple change, under headword `aYca`:
```
.{#aYca#}¦ r. 1st cl. ({#u.#}) ({#aYcati#})
.²1 To adore, to worship, to treat with respect, ({#Ya, u.#}) ({#aMcati-te#})
.²2 To go, to approach.
.²3 To ask or beg.
.²4 To speak indistinctly. With {#pra,#} to move in an eastern direction; with
{#prati,#} to go westerly; with {#ut,#} to go northerly; with {#ava,#} to move
---- next two lines, current
southerly; with {#parA,#} to turn aside or away. r. 1st and 10th cl. ({#aMcati
aMcayati#}) To discriminate, to individualize, to possess especially. See
---- these two lines, after change
southerly; with {#parA,#} to turn aside or away. r. 1st and 10th cl. ({#aMcati#}
{#aMcayati#}) To discriminate, to individualize, to possess especially. See
---- remaining last line of this entry in wil.txt
{#aca.#}
```

**Comment by funderburkjim** [comment]
There is a similar issue with italic markup, for about 81 cases.    Might as well normalize these cases  also, so italic markup is closed within lines of wil.txt.

**Comment by funderburkjim** [comment]
These corrections have been installed.

**Comment by gasyoun** [comment]
> not closed within a line

Well done!
